config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  resources :authors
  resources :recipe_types
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'recipes#index'
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg border-bottom border-5 border-dark">
  <div class="container-fluid">
    
      <div class="navbar-nav">
        <ul class="nav">
          <li class="nav-item  border border-2 rounded">
            <%= link_to 'Recipes', recipes_path(), class:"nav-link" %>
          </li>
          <li class="nav-item  border border-2 rounded">
            <%= link_to 'Authors', authors_path(), class:"nav-link" %>
          </li>
          <li class="nav-item border border-2 rounded">
            <%= link_to 'Categories', categories_path(), class:"nav-link" %>
          </li>
          <li class="nav-item  border border-2 rounded">
             <%= link_to 'Recipe Types', recipe_types_path(), class:"nav-link" %>
          </li>
         </ul>
    
      </div>
      <h3>CookBook <sub>by Matias Bojko</sub></h3>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cook Book!</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>